options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running Terraform APPLY"
        echo "Bucket: ${_BACKEND_CONFIG_BUCKET}"
        echo "Prefix: ${_BACKEND_CONFIG_PREFIX}"
        echo "Var file: ${_VAR_FILE}"

  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        ls -al
        cd terraform

        terraform init \
          -backend-config="${_BACKEND_CONFIG_BUCKET}" \
          -backend-config="${_BACKEND_CONFIG_PREFIX}"

        terraform apply \
          -auto-approve \
          -var-file="${_VAR_FILE}"

